// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVtUA9QQhjZwc-4mbru3FrFpZlQUean_A',
    appId: '1:623790126923:web:6d7c234946ade298b65ace',
    messagingSenderId: '623790126923',
    projectId: 'studyfriend',
    authDomain: 'studyfriend-2c3a6.firebaseapp.com',
    storageBucket: 'studyfriend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF98-wmmHqZU6WV0orlrVU4U1o_EQ-p18',
    appId: '1:623790126923:android:59fc726fbc128287b65ace',
    messagingSenderId: '623790126923',
    projectId: 'studyfriend',
    storageBucket: 'studyfriend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7yj2f00EIU3SgVcsFsHeqSydsOYIrTn4',
    appId: '1:623790126923:ios:c7f75bbc5b27ae53b65ace',
    messagingSenderId: '623790126923',
    projectId: 'studyfriend',
    storageBucket: 'studyfriend.firebasestorage.app',
    iosBundleId: 'com.example.kidfuel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7yj2f00EIU3SgVcsFsHeqSydsOYIrTn4',
    appId: '1:623790126923:ios:c7f75bbc5b27ae53b65ace',
    messagingSenderId: '623790126923',
    projectId: 'studyfriend',
    storageBucket: 'studyfriend.firebasestorage.app',
    iosBundleId: 'com.example.kidfuel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVtUA9QQhjZwc-4mbru3FrFpZlQUean_A',
    appId: '1:623790126923:web:07390243a3f0b285b65ace',
    messagingSenderId: '623790126923',
    projectId: 'studyfriend',
    authDomain: 'studyfriend-2c3a6.firebaseapp.com',
    storageBucket: 'studyfriend.firebasestorage.app',
  );
}
